set gaSet(sw)          "0"
set gaSet(dbrSW)       ""
set gaSet(swPack)      "??"
set gaSet(DutFullName) "ETX-2I-B_RJIO/H/WR/2SFP/8SFP"
set gaSet(DutInitName) "ETX-2I-B_RJIO.H.WR.2SFP.8SFP.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/ConfFiles/rtr2ibRJIO.txt"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
