set gaSet(sw)          "??"
set gaSet(dbrSW)       "6.7.1(0.53)"
set gaSet(swPack)      "SW3688"
set gaSet(DutFullName) "ETX-2I-B_LY/WR/2SFP/4UTP/RTR"
set gaSet(DutInitName) "ETX-2I-B_LY.WR.2SFP.4UTP.RTR.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.8.2(0.75)_LY/sw-pack_2iB.bin"
set gaSet(DefaultCF) "C:/AT-ETX-2iB/ConfFiles/DefaultConf/LY/LY_etx2iB_ztp_minimal_Rev1.cfg"
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data-6ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "86"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
