set gaSet(sw)          "?"
set gaSet(dbrSW)       "6.8.5(1.88)"
set gaSet(swPack)      "SW3358"
set gaSet(DutFullName) "ETX-2I-B/WR/2SFP/4UTP/RTR"
set gaSet(DutInitName) "ETX-2I-B.WR.2SFP.4UTP.RTR.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.8.5(1.88)/sw-pack_2iB_6_8_5-1_88.bin"
set gaSet(DefaultCF) ""
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data-6ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "86"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
