set gaSet(sw)          "??"
set gaSet(dbrSW)       "6.7.1(0.136)"
set gaSet(swPack)      "SW3376"
set gaSet(DutFullName) "ETX-2I-B_MOT/H/WR/2SFP/4SFP/BC/RTR"
set gaSet(DutInitName) "ETX-2I-B_MOT.H.WR.2SFP.4SFP.BC.RTR.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) "c:/aa"
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/Users/ate-j-r/Desktop/etxa_6.7.1.136_20230419/sw-pack_2iB_10x1G.bin"
set gaSet(DefaultCF) "c:/aa"
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data-6ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "C1"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
