set gaSet(sw)          "??"
set gaSet(dbrSW)       "??"
set gaSet(swPack)      "SW3630"
set gaSet(DutFullName) "ETX-2I-B_CEL/H/WR/2SFP/8SFP"
set gaSet(DutInitName) "ETX-2I-B_CEL.H.WR.2SFP.8SFP.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.7.1(058)_CELL/sw-pack_2iB_10x1G_sr.bin"
set gaSet(DefaultCF) "C:/AT-ETX-2iB/ConfFiles/DefaultConf/Cellcom/CELL_ETX-2IB-10x1G_Rev1.TXT"
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data_10ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "88"
set gaSet(dbrBVerSw)   "SW3326"
set gaSet(dbrBVer)     "??"
