set gaSet(sw)          "??"
set gaSet(dbrSW)       "6.7.1(0.15)"
set gaSet(swPack)      "SW3375"
set gaSet(DutFullName) "ETX-2I-B/H/WR/2SFP/4SFP4UTP/DRC"
set gaSet(DutInitName) "ETX-2I-B.H.WR.2SFP.4SFP4UTP.DRC.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.7.1(0.15)/sw-pack_2iB_10x1G_sr.bin"
set gaSet(DefaultCF) ""
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data_10ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "88"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
