set gaGui(xy) +327+51
set gaSet(entDUT) "ETX-2I-B/WR/2SFP/4UTP/RTR"
set gaSet(DutInitName) "ETX-2I-B.WR.2SFP.4UTP.RTR.tcl"
set gaSet(performShortTest) "0"
set gaSet(eraseTitle) 0
set gaSet(pioType) "Usb"
set gaSet(enDownloadsBefore) "1"
set gaSet(radTsts) "Full"
set gaSet(enUsbTest) "0"
set gaSet(readTrace) "1"
set gaSet(enSerNum) "0"
