set gaSet(sw)          "0"
set gaSet(dbrSW)       "6.6.1(1.26)"
set gaSet(swPack)      "SW3488"
set gaSet(DutFullName) "ETX-2I-B_RJIO/H/WR/2S6H/8SFP"
set gaSet(DutInitName) "ETX-2I-B_RJIO.H.WR.2S6H.8SFP.tcl"
set gaSet(RJIOCF) "C:/AT-ETX-2iB/ConfFiles/data_1_2_2ibRJIO.txt"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/rtr2ibRJIO.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.3.1(0.42)_rjio/sw-pack_2iB_10x1G_sr.bin"
set gaSet(DefaultCF) "C:/AT-ETX-2iB/ConfFiles/DefaultConf/RJIO/RJIO_DHCPv6 ETX-2iBpre-config_rev1.txt"
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "c:/aa"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "88"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
