set gaSet(sw)          "??"
set gaSet(dbrSW)       "??"
set gaSet(swPack)      "SW3376"
set gaSet(DutFullName) "ETX-2I-B/H/WR/2SFP/4SFP4UTP/DRC/RTR"
set gaSet(DutInitName) "ETX-2I-B.H.WR.2SFP.4SFP4UTP.DRC.RTR.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.6.1(0.23)/sw-pack_2ib_10x1g.bin"
set gaSet(DefaultCF) ""
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data_10ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "88"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "??"
