set gaSet(sw)          "??"
set gaSet(dbrSW)       ""
set gaSet(swPack)      "SW3600"
set gaSet(DutFullName) "ETX-2I-B/AC/V/2SFP/4UTP"
set gaSet(DutInitName) "ETX-2I-B.AC.V.2SFP.4UTP.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.5.1(0.27)/etxa_6.5.1.27_20180917_sw-pack_2iB_10x1G_sr.bin"
set gaSet(DefaultCF) ""
set gaSet(VCF) "C:/AT-ETX-2iB/ConfFiles/data_V.txt"
set gaSet(2iBCF) "c:/aa"
set gaSet(DNFVCF) "C:/AT-ETX-2iB/ConfFiles/dnfv.txt"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "2.40GHz"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "88"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
