set gaSet(sw)          "??"
set gaSet(dbrSW)       "6.0.1(0.32)"
set gaSet(swPack)      "SW3358"
set gaSet(DutFullName) "ETX-2I-B/DDC/V/2SFP/4UTP/RTR"
set gaSet(DutInitName) "ETX-2I-B.DDC.V.2SFP.4UTP.RTR.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/SW/6.0.1_0.32/etxa_6.0.1(0.32)_sw-pack_2iB_10x1G.bin"
set gaSet(DefaultCF) ""
set gaSet(VCF) "C:/AT-ETX-2iB/ConfFiles/data_V.txt"
set gaSet(2iBCF) "c:/aa"
set gaSet(DNFVCF) "C:/AT-ETX-2iB/ConfFiles/dnfv.txt"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
