set gaSet(sw)          "??"
set gaSet(dbrSW)       "6.4.0(0.27)"
set gaSet(swPack)      "SW3375"
set gaSet(DutFullName) "ETX-2I-B/WR/2SFP/4SFP/BC"
set gaSet(DutInitName) "ETX-2I-B.WR.2SFP.4SFP.BC.tcl"
set gaSet(RJIOCF) "c:/aa"
set gaSet(DGaspCF) "C:/AT-ETX-2iB/ConfFiles/Dying Gasp.txt"
set gaSet(ExtClkCF) ""
set gaSet(RTRCF) "C:/AT-ETX-2iB/ConfFiles/RtRtest.txt"
set gaSet(BootCF) "C:/download/boot 1.10/vxboot.bin"
set gaSet(SWCF) "C:/download/6.4.0(0.27)/sw-pack_2ib_10x1g_sr.bin"
set gaSet(DefaultCF) ""
set gaSet(VCF) "c:/aa"
set gaSet(2iBCF) "C:/AT-ETX-2iB/ConfFiles/data-6ports.txt"
set gaSet(DNFVCF) "c:/aa"
set gaSet(dnfvProject) "??"
set gaSet(dnfvEC) "??"
set gaSet(dnfvCPU) "??"
set gaSet(licDir) "??"
set gaSet(dnfvVer) "??"
set gaSet(cpld)      "C1"
set gaSet(dbrBVerSw)   "SW3327"
set gaSet(dbrBVer)     "1.10"
